### ISSUE TITLE
ranger_http/server.go has some broken import libraries

### ISSUE THREAD

**Issue by mark-lauyq** [deliveryhero/go-ranger#69]
"gopkg.in/throttled/throttled.v2"
"gopkg.in/throttled/throttled.v2/store/memstore"

These 2 libraries no longer exist as the developer has changed over to github instead

https://github.com/throttled/throttled/issues/44

**Comment by wilsont** [comment]
can you create a PR to fix this?

**Comment by mark-lauyq** [comment]
Done
